name: Auth CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: auth

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.10.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "poletas" #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL}}
          appdir: "./auth"
