name: Client CI

on:
  pull_request:
    branches: "client/**"

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: client

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: yarn install --frozen-lockfile
      - run: yarn run build:prod
